// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var brick = "<div class='brick small'><div class='delete'>&times;</div></div>";
    $(document).on("click", ".gridly .delete", function(event) {
      var $this;
      event.preventDefault();
      event.stopPropagation();
      $this = $(this);
      $this.closest('.brick').remove();
      return $('.gridly').gridly('layout');
    });
    $(document).on("click", ".add", function(event) {
      event.preventDefault();
      event.stopPropagation();
      $('.gridly').append(brick);
      return $('.gridly').gridly();
    });
    $(".brick").on({
		mousedown:function(e){
			window.mousedownPageX = e.pageX;
			window.mousedownPageY = e.pageY;
        },
        mousemove:function(e){
        	window.mousemovePageX = e.pageX;
			window.mousemovePageY = e.pageY;
	    },
        mouseup:function(e){
        	window.mouseupPageX = e.pageX;
			window.mouseupPageY = e.pageY;
        	window.diametre = Math.sqrt((window.mouseupPageX-window.mousedownPageX)*(window.mouseupPageX-window.mousedownPageX)+(window.mouseupPageY-window.mousedownPageY)*(window.mouseupPageY-window.mousedownPageY));
			// IE9 不在 F12 下不支持控制台日志输出
			if(window.console){
				console.log(window.diametre);
			}
			if(window.diametre < 2){
				window.location = $(e.currentTarget).attr("url");
			}
	    }
    });
    return $('.gridly').gridly();
  });

}).call(this);
